import type { ComponentType } from "react";
import { S01, S02, S03, S04, S04B, S05, S05B } from "./act1";
import { S06, S07, S09, S10 } from "./act2";
import { S11, S11B, S11C, S13, S14, S15, S15B } from "./act3";
import { S16, S17, S18, S19, S20, S21 } from "./act4";

export type SlideDef = {
  id: number;
  title: string;
  act: string;
  steps: number;
  notes: string;
  Component: ComponentType<{ step?: number }>;
};

const d = (
  id: number,
  title: string,
  act: string,
  Component: ComponentType<{ step?: number }>,
  notes: string,
  steps = 1,
): SlideDef => ({ id, title, act, Component, notes, steps });

export const slides: SlideDef[] = [
  d(1, "Billingen", "Öppning", S01, "[Gå fram. Stå still. Se ut över rummet innan du börjar.]\n\nHur bygger man en destination?\n\n[Paus – tre sekunder.]\n\nDet korta svaret är: det gör man inte ensam.\n\nDet längre svaret handlar om en gåva, ett vägval och väldigt många människor som valde att dra åt samma håll.\n\nDet är den resan jag vill ta med er på i dag."),
  d(2, "Ett beslut 1967", "Akt 1", S02, "Vår berättelse börjar inte med en strategi.\n\nDen börjar med två människor.\n\nArne Sandberg hade sålt Uno-X. Han och Maja kunde ha placerat pengarna och gått vidare.\n\nMen de gjorde ett annat val.\n\nDe sa: ”Vi gör något roligt i stället.”\n\nOch med ”roligt” menade de något som skulle bli värdefullt för en hel stad."),
  d(3, "Gåvan", "Akt 1", S03, "1970 stod ett helt friluftsparadis färdigt.\n\nHotell, bad, skidbacke, tennis, fotboll och motionsspår.\n\nSedan överlät Arne och Maja området till kommunen.\n\nFör en krona.\n\n[Paus. Låt siffran stå ensam.]\n\nEn krona var förstås inte värdet.\n\nDet var priset för ett förtroende.\n\nOch ett sådant förtroende kommer med ett ansvar: att inte bara bevara det man fått, utan att göra det relevant också för nästa generation."),
  d(4, "Vägvalet", "Akt 1", S04, "Men en gåva är inte färdig för all framtid.\n\nAnläggningar åldras. Vanor förändras. Konkurrensen ökar. Och vintern blir mindre förutsägbar.\n\nTill slut stod vi inför ett vägval:\n\nSkulle vi förvalta minnet av det som Billingen hade varit?\n\nEller skulle vi utveckla själva idén?\n\n[Vänd dig mot publiken.]\n\nHur många här förvaltar just nu något som egentligen behöver uppfinnas på nytt?\n\n[Kort paus. Be inte om muntliga svar.]"),
  d(5, "Eldsjälarna", "Akt 1", S04B, "Svaret började inte i kommunhuset.\n\nDet började hos människorna som redan använde berget.\n\nLotta Stigsdotter samlade föreningarna. Särintressen fick bli ett gemensamt intresse. Tillsammans formulerade de en riktning och bildade Billingens fritidsområde ekonomisk förening – BFEF.\n\nDe gjorde något som är helt avgörande i destinationsutveckling:\n\nDe gick från många önskemål till en gemensam röst.\n\nDet gav kommunen något att ta ställning till – och något att tro på."),
  d(6, "Riktningen", "Akt 1", S05, "Det hade varit lätt att börja med en inköpslista.\n\nEn ny backe. Ett längre spår. En bättre arena.\n\nMen en lista håller inte ihop en utvecklingsresa.\n\nDet gör en riktning.\n\nVår blev: södra och västra Sveriges bästa outdoordestination – året runt.\n\nDen formuleringen blev viktig, eftersom planerna skulle hinna förändras. Ägare skulle bytas. Förutsättningarna skulle skifta.\n\nMen riktningen behövde ligga fast."),
  d(7, "Läget", "Akt 1", S05B, "Billingen har en ovanlig tillgång.\n\nDet ligger inte vid sidan av staden. Det ligger mitt i människors vardag – och nära en stor marknad.\n\nFem minuter med bil från centrum. Cirka en timme med tåg från Göteborg och cirka två från Stockholm.\n\nNärheten sänker tröskeln för besökaren.\n\nMen den gör också att varje investering kan skapa värde varje dag för dem som redan bor här."),
  d(8, "Modet", "Akt 2", S06, "Sedan kom beslutet.\n\n288 miljoner kronor i beslutad total investeringsbudget.\n\n[Paus.]\n\nDet är lätt att applådera en investering när resultatet redan syns.\n\nDet svåra är att fatta beslutet innan gästnätterna ökar, innan rubrikerna kommer och innan man vet exakt hur varje del ska landa.\n\nDärför vill jag lyfta politiken – över blockgränser och mandatperioder.\n\nDet avgörande var inte bara modet att börja.\n\nDet var uthålligheten att fortsätta."),
  d(9, "Tre förflyttningar", "Akt 2", S07, "Pengarna byggde förstås anläggningar.\n\nMen det viktigaste var vad anläggningarna gjorde möjligt.\n\n[Klicka fram en rörelse i taget.]\n\nVi gick från väderberoende till större snösäkerhet.\n\nFrån separata delar till en plats som hänger ihop.\n\nOch från en tydlig vintersäsong till fler anledningar att komma – och komma tillbaka – under hela året.\n\nPlanerna förändrades. Ägare byttes. Förutsättningarna hann skifta.\n\nMen riktningen låg fast."),
  d(10, "Dubbla nyttan", "Akt 2", S09, "Här finns en viktig falsk motsättning.\n\nVi behöver inte välja mellan en bra plats att besöka och en bra plats att leva på.\n\nBarnets fritid, föreningens arena, företagens attraktionskraft och besökarens upplevelse kan växa ur samma investering.\n\nNär vi lyckas blir turismutveckling inte något som görs vid sidan av samhällsutvecklingen.\n\nDet blir en del av den."),
  d(11, "Året runt", "Akt 2", S10, "”Året runt” får inte bara vara en formulering i en vision.\n\nDet är en affärsmodell.\n\nFler säsonger sprider risken. De ger jämnare efterfrågan, bättre användning av infrastrukturen och starkare förutsättningar för arbetstillfällen över året.\n\nIngen enskild säsong ska behöva bära hela platsen.\n\n[Räkna inte upp bilderna. Låt dem visa variationen.]"),
  d(12, "Sälj målet", "Akt 3", S11, "Här finns en lärdom som jag tror är relevant långt utanför Billingen.\n\nVi kan säga att vi har elva kilometer konstsnöspår.\n\nDet är korrekt – men det är inte det gästen egentligen köper.\n\nGästen köper möjligheten att klara sitt första Vasalopp. Att nå ett mål. Att bli den person hon hoppas kunna bli.\n\nVi säljer alltså inte bara spåret.\n\nVi hjälper människor på deras resa.\n\nOch gästen möter inte våra organisationsgränser. Hon möter ankomsten, aktiviteten, maten, boendet – och känslan som avgör om hon vill komma tillbaka.\n\nDet är skillnaden mellan att marknadsföra en anläggning och att utveckla en destination."),
  d(13, "Här kunde resan ha stannat", "Akt 3", S11B, "Men en destination blir inte komplett genom kommunala investeringar ensamma.\n\nNär beslutet om Billingen fattades var hotellet fortfarande en svag länk.\n\nDet var slitet. Framtiden var osäker. Och den förändring som behövdes hade ännu inte blivit verklighet.\n\nHär kunde berättelsen faktiskt ha stannat.\n\nVi kunde ha fått ett fantastiskt friluftsområde – men ingen komplett destination.\n\n[Paus. Byt sedan slide utan att fortsätta prata under övergången.]\n\n[Sources]\nBild: File:First Hotel Billingehus.jpg, foto I99pema, 2019-08-06, CC BY-SA 4.0, https://commons.wikimedia.org/wiki/File:First_Hotel_Billingehus.jpg (nedladdad och lokalt lagrad 2026-08-21).\nDatering av hotellets läge före omvandlingen: Sveriges Radio 2017, https://www.sverigesradio.se/artikel/6607828 (endast referens, ingen bild använd)."),
  d(14, "Förvandlingen", "Akt 3", S11C, "Sedan såg Lotus Group något annat.\n\nDär andra såg risk såg de potentialen i platsen, utsikten och den offentliga satsning som redan hade börjat förändra berget.\n\nDe tog över Billingehus och inledde en omfattande omvandling. Hotellet återöppnade 2023. Därefter kom Earth Spa, Elevation Spa och Bergasalen.\n\n[Klicka fram bevisen lugnt.]\n\nI dag har vi en kongresshall för upp till 750 personer.\n\n235 hotellrum.\n\nRestauranger, två spa och infinitypooler.\n\nOch naturen direkt utanför dörren.\n\n[Kort paus.]\n\nJag tänker uttrycka det subjektivt – men uppriktigt:\n\nJag tycker att vi nu har Västsveriges fräckaste konferensprodukt.\n\nInte för att varje enskild del måste vara störst.\n\nUtan för att kombinationen är så svår att kopiera.\n\nKommunens investering stärkte platsens potential. Den privata investeringen gjorde helheten komplett.\n\nNär offentligt och privat började dra åt samma håll fick båda investeringarna större värde.\n\n[Sources]\nBilder: Billingehus/Lotus Hotel Group officiella pressbilder – bergasalen-kongress-night-billingehus-skovde-0137 och pool-ute-elevation-spa-billingehus-2116, https://billingehus.com/mote-event/kongress/ och https://billingehus.com/en/spa-wellness/elevation-spa/ (nedladdade lokalt 2026-08-21; pressbildsgalleri: https://www.mynewsdesk.com/se/lotushotelgroup/tag/billingehus). Upphovsrätt Lotus Hotel Group – använd enligt medievillkor.\nFakta: Bergasalen 700 kvm, upp till 750 personer i biosittning samt 235 hotellrum och leder/konstsnöspår cirka 2 minuter bort – https://billingehus.com/mote-event/kongress/. Infinitypool inne och två utomhuspooler – https://billingehus.com/en/spa-wellness/elevation-spa/.\nÅrtal: Lotus Hotel Group anger att Billingehus välkomnades hösten 2021 och ägs/drivs sedan 2022, nya Billingehus öppnade sommaren 2023, Earth Spa våren 2024 följt av Elevation Spa och kongresshall – https://lotushotelgroup.se/om-oss/var-historia/. Därför formuleringen 2021–2022.", 5),
  d(15, "Människorna", "Akt 3", S13, "Så vem byggde destinationen?\n\n[Paus.]\n\nFöreningarna gjorde det.\n\nMedarbetarna gjorde det. Företagen, politiken, kommunen, hotellet, Turistrådet och invånarna gjorde det.\n\nOlika människor tog ansvar vid olika tidpunkter.\n\nNågon behöver hålla ihop helheten – men ingen enskild aktör äger framgången.\n\n[Vänd dig mot publiken.]\n\nVilken aktör saknas fortfarande runt ert bord hemma?\n\n[Kort paus.]"),
  d(16, "Tillsammans når vi längre", "Akt 3", S14, "Och här vill jag vända mig direkt till er i rummet.\n\nSamarbetet med Turistrådet Västsverige har gett oss sådant som är svårt att bygga ensam: kompetens, räckvidd, kampanjer, pressresor och marknadsbearbetning.\n\nDet handlar inte om att lämna över sin marknadsföring till någon annan.\n\nDet handlar om att koppla den lokala berättelsen till en kraft som når längre.\n\nTillsammans har vi kunnat göra Billingen mer synligt och mer relevant än vi hade kunnat på egen hand."),
  d(17, "Evenemangen", "Akt 3", S15, "Evenemang mäts ofta i publik och gästnätter.\n\nMen deras kanske största värde är att de tvingar fram utveckling.\n\nEtt evenemang sätter en deadline. Det stresstestar infrastrukturen. Det tränar samarbetet. Och det ger platsen en berättelse som når långt utanför kommunen.\n\nSM-veckan 2023 visade vad vi kunde göra.\n\nEnduro-VM 2025 höjde kraven.\n\nOch SM-veckan 2027 blir nästa test – inte bara av våra arenor, utan av vår förmåga att agera som en destination."),
  d(18, "Billingetrollet", "Akt 3", S15B, "Men en destination kan inte bara bestå av investeringar, tävlingar och nyckeltal.\n\nDen behöver också en själ.\n\nFör många barn är Billingen inte i första hand ett friluftsområde.\n\nDet är platsen där Billingetrollet bor.\n\nGenom Billingetrollets skog, skogsbion och skogsteatern får berget en berättelse som barn kan kliva in i.\n\nSkogsteaterns premiärsäsong 2025 lockade omkring 2 500 besökare.\n\nDet är mer än en aktivitet.\n\nDet är ett minne – och kanske början på en livslång relation till platsen.\n\n[Sources]\nSiffra 2 500 besökare (skogsteaterns premiärsäsong 2025): Next Skövde, pressmeddelande 25 augusti 2025 – samma källa som anges på sliden."),
  d(19, "Hållbarheten", "Akt 4", S16, "Hållbarhet får lätt bli ett ord som läggs ovanpå allt annat.\n\nFör oss behöver det märkas i hur platsen fungerar.\n\nAtt onödig miljöpåverkan minimeras. Att platsen är bra för både boende och besökare. Att kapacitet används när den annars står tom. Och att verksamheter och arbetstillfällen blir mer robusta.\n\nBillingen och Billingehus är Skaraborgs kandidat till Årets Hållbarhetskliv 2026.\n\nDet är vi stolta över.\n\nMen den verkliga prövningen är inte utmärkelsen.\n\nDet är de val vi gör varje dag efter den."),
  d(20, "Gästnätterna", "Akt 4", S17, "Så – syns utvecklingen i resultaten?\n\nJa.\n\n[Klicka fram ett år i taget.]\n\n203 000 kommersiella gästnätter 2023.\n\n229 209 år 2024.\n\nOch preliminärt 245 885 år 2025.\n\nDet är den starkaste noteringen hittills – ungefär tjugo procents ökning på två år.\n\nMen här ska vi vara noggranna:\n\nBillingen är en av flera motorer bakom utvecklingen. Inte ensam förklaring.\n\nDet viktiga är att allt fler väljer att stanna i Skövde.", 4),
  d(21, "Värdet", "Akt 4", S18, "Gästnätter är ett viktigt mått – men inte hela värdet.\n\nTurismkonsumtionen i Skövde ökade från 1,351 miljarder kronor 2023 till 1,484 miljarder 2025.\n\n[Använd endast formuleringen om årtal och belopp är verifierade i projektets källa.]\n\nDet visar att besöken lämnar ett större ekonomiskt avtryck.\n\nMen allt värde syns inte i kronor.\n\nDet syns också i föreningslivet, folkhälsan, stoltheten – och i ett Skövde som blir lättare att välja både för besökare och för människor som funderar på att bo och arbeta här."),
  d(22, "Nästa kapacitetsfråga", "Akt 4", S19, "Det vore frestande att sluta berättelsen här.\n\nMed rekordsiffror och en bild av att vi är färdiga.\n\nMen destinationsutveckling blir aldrig färdig.\n\nSärskilt tisdag till torsdag räcker hotellkapaciteten återkommande inte till.\n\nHär behöver vi skilja mellan affärsresande, evenemang och fritidsresande. Men tillsammans påverkar de stadens kapacitetsbehov.\n\nDet är nästa fråga vi behöver lösa.\n\nFör varje framgång skapar också nästa flaskhals."),
  d(23, "Vårt ansvar", "Avslutning", S20, "Så – hur bygger man en destination?\n\n[Paus. Knyt tydligt tillbaka till öppningsfrågan.]\n\nMan börjar med en riktning.\n\nMan vågar fatta beslut innan alla svar finns.\n\nMan bygger ett system, inte en samling projekt.\n\nMan gör det tillsammans.\n\nOch man håller i – längre än en budget, en mandatperiod eller en enskild eldsjäl.\n\n[Klicka fram slutmeningen. Sänk tempot.]\n\nDet började med två människors dröm – och en gåva för en krona.\n\nDet fortsatte genom hundratals beslut och väldigt många människors arbete.\n\n[Paus.]\n\nVårt ansvar är att lämna över något ännu bättre.\n\n[Var tyst. Låt slutbilden stå. Tacka inte omedelbart.]", 2),
  d(24, "Håll kontakt", "Outro", S21, "Detta är en passiv holding slide som visas först efter den muntliga avslutningen, under applåd eller frågor.\n\nSäg inget nytt här. Om en kort kommentar behövs:\n\n”Vill ni följa resan vidare finns Billingen på billingen.se och i våra sociala kanaler.”\n\nGå sedan direkt till frågor."),
];
